version: 2
jobs:
  user1:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "SOLO"
  user2:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "DT"
  # build:
  #    docker:
  #      - image: circleci/node:latest
  #    steps:
  #      - checkout
  #      - run: npm install
  #      - run: CI=true npm run build
workflows:
  version: 2
  users:
    jobs:
      - user1
      - user2