version: 2.1 
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: npm install
       - run: npm run build
workflows:
  version: 2
  build:
    jobs:
      - build